### ISSUE TITLE
adduser fails with ABEND S0C4

### ISSUE THREAD

**Issue by desrig869** [MVS-sysgen/RAKFCL#2]
rx adduser brian                                          
                                                          
 BRX0003E - ABEND CAUGHT IN BREXX/370                     
                                                          
 USER JES       RX        ABEND S0C4                      
 EPA 000ACDF0  PSW 078D3000 000B11F8  ILC 04  INTC 0010   
 GR 0-3   00000000  00170488  A2969997  0015072C          
 GR 4-7   001AFC78  001BCAD8  00000000  00000000          
 GR 8-11  00000004  001AF528  000B1444  00170420          
 GR 12-15 000B11B8  00170424  500B11E6  00000000          
                                                          
 READY                                                    
                                                          

Also results in EMPTY USERS file

RX listuser works ok so it seems it fails when writing to the file.

The MVS system was sysgened using your MVS-sysgen/sysgen
Also fails on MVS-TK5

JES user has RAKFADM  and ADMIN in USERS file

**Comment by mainframed** [comment]
Thanks for reporting this, i'll check it out.

**Comment by mainframed** [comment]
I believe I've fixed this, please test. 

With a clean MVS/CE install (or after rebuilding your user file and removing the RAKFCL line from the dataset `MVP.MVPDB`) you can do the following (from the TSO ready prompt):

`RX MVP UPDATE`
`RX MVP INSTALL RAKFCL`

Then you can use ADDUSER, ADDGROUP, ADDSD, etc.

**Comment by desrig869** [comment]
I can confirm this issue is now fixed
